# Basic Congiguration Control
---
- name: roles/base/tasks/main.yml
  command: echo

- name: Check if hosts exists
  stat: 
    path: /etc/ansible/hosts
  register: etc_ansible_hosts

- name: Check if localhost.yml exists
  stat: 
    path: /etc/ansible/host_vars/localhost.yml
  register: host_vars_localhost_yml

- name: Check minimum requirement
  fail:
  when: |
    etc_ansible_hosts.stat.exists != true        or
    host_vars_localhost_yml.stat.exists != true

- set_fact: 
    distribution_ok: false

- name: Check for CentOS7
  set_fact:
    distribution_ok: true
  when: |
    not USE_AMAZONLINUX2 
    and ansible_distribution == 'CentOS' 
    and ansible_distribution_version == '7'

- name: Check for AmazonLinux2
  set_fact:
    distribution_ok: true
  when: |
    USE_AMAZONLINUX2 
    and ansible_distribution == 'Amazon'
    and ansible_distribution_version == '2'

# - debug: var=distribution_ok

- name: Check distribution
  fail:
  when: not distribution_ok

- name: Check if EC2
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloud

- name: Do ec2 specific tasks
  import_tasks: ec2.yml
  when: 
    - cloud.stat.exists == true
    - _V == '7'

- import_tasks: phprepo.yml
- import_tasks: mandatory.yml
- import_tasks: time.yml
- import_tasks: prompt.yml
- import_tasks: users.yml
- import_tasks: security.yml
- import_tasks: locale.yml
  when: SYSTEM_LOCALE == 'ja'
